### ISSUE TITLE
NativeScript 7 update

### ISSUE THREAD

**Issue by kaanguru** [javierpal/nativescript-cscreenshot#12]
Is NativeScript 7 update coming anytime soon?

https://nativescript.org/blog/nativescript-7-for-plugin-authors/

**Comment by PhilippS93** [comment]
see https://github.com/enduco/nativescript-cscreenshot

**Comment by kaanguru** [comment]
it says: 

> @enduco/nativescript-cscreenshot is not a valid NativeScript plugin. Verify that the plugin package.json file contains a nativescript key and try again.

**Comment by ray007** [comment]
Setting the `compilerOptions.target` in `src/tsconfig.json` to `es2017` makes things work again.

Should be an easy change to make and publish.

**Comment by javierpal** [comment]
I update the plugin to Nativescript 8.0
