### ISSUE TITLE
Screenshot doesn't expand ScrollView

### ISSUE THREAD

**Issue by connorsleight** [javierpal/nativescript-cscreenshot#2]
### Which platform(s) does your issue occur on?
Android (Emulator on Android 9)
Not tried iOS as there isnt a need in my app for it

### Please, provide the following version numbers that your issue occurs with:

- CLI: 6.4.1
- Cross-platform modules: 6.4.2
- Runtime(s): 6.4.1
- Plugin(s): nativescript-cscreenshot: 1.0.2

### Please, tell us how to recreate the issue in as much detail as possible. 
Add a scrollview and make it have content longer than the screen size. Take the screenshot and check the image, it will only match what was in the view at the time

### Is there any code involved? 
Just using the sample code but with a scrollview in the html file

**Comment by javierpal** [comment]
Mmm weird, I did some tests rewarding that but seems to be working fine, do you have a screenshot or something? Sometimes Nativescript does weird things while using scrollview, can you check using a different layout?
