### ISSUE TITLE
Cannot read property 'android' of undefined

### ISSUE THREAD

**Issue by atmanegara** [javierpal/nativescript-cscreenshot#38]
i'm using NS 8, Javascript Plain

![image](https://user-images.githubusercontent.com/9096711/139214393-6778ef93-f0a7-4a3d-ac9e-8736807d128c.png)
![image](https://user-images.githubusercontent.com/9096711/139214520-943dcd85-da21-4e01-a314-23b4fca407d7.png)

**Comment by javierpal** [comment]
Try to reset you nativescript platforms maybe that could be the problem. i'm going to check it out anyways.
