### ISSUE TITLE
Change background of image

### ISSUE THREAD

**Issue by martintschemernjak** [javierpal/nativescript-cscreenshot#5]
### If the demo apps cannot help and there is no issue for your problem, tell us about it
Please, ensure your title is less than 63 characters long and starts with a capital
letter.

### Which platform(s) does your issue occur on?
- Android 
- Android 10
- device, Pixel 3

### Please, tell us how to recreate the issue in as much detail as possible. 
If i use the plugin to make a screenshot of a graph element, the background of the image is transparent as a png or black if i use a jpg.

Is there a way where i can set the background of the image to for example white?

### Is there any code involved? 

```
 import { Cscreenshot } from 'nativescript-cscreenshot';

let screen = new Cscreenshot();

export class MeasurementGraphComponent implements OnInit {
    @ViewChild("main", { static: true }) view: ElementRef;

takeScreenshot() {
        screen.take(this.view.nativeElement, (image: ImageSource) => {

            const data = this.fileHandler.saveGraphScreenshot(image, this.configService.getConfig().graphShare.folderName, this.configService.getConfig().graphShare.baseFileName)

            if (data.saved) {
                console.log("Image saved successfully!");
            }
        });
    }
}


```

and the html:
`<RadCartesianChart tkExampleTitle tkToggleNavButton id="main" #main ref="main">`

**Comment by javierpal** [comment]
You need to take a screenshot of a component that has a background, because without it, is going to take the transparency of the component.
